apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.serviceName }}-{{ .Values.instanceId }}
spec:
  selector:
    app: {{ .Values.mysql.name }}
    instance: {{ .Values.instanceId }}
  ports:
  - port: {{ .Values.mysql.port }}
    targetPort: {{ .Values.mysql.port }}

