apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mysql.name }}-{{ .Values.instanceId }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.mysql.name }}
      instance: {{ .Values.instanceId }}
  template:
    metadata:
      labels:
        app: {{ .Values.mysql.name }}
        instance: {{ .Values.instanceId }}
    spec:
      containers:
      - name: mysql
        image: {{ .Values.mysql.image }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.mysql.rootPassword }}
        ports:
        - containerPort: {{ .Values.mysql.port }}
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: {{ .Values.mysql.pvcName }}-{{ .Values.instanceId }}
--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mysql.pvcName }}-{{ .Values.instanceId }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mysql.storage }}
  storageClassName: {{ .Values.mysql.storageClassName }}


